development:
  server: "http://yofaye.herokuapp.com/faye"
  secret_token: "skill123"
test:
  server: "http://yofaye.herokuapp.com/faye"
  secret_token: "skill123"
production:
  server: "http://yofaye.herokuapp.com/faye"
  secret_token: "skill123"
  signature_expiration: 86400 # one day
